
language: php

# The platforms you wants to test on
dist: trusty

os:
  - linux

# Install google chrome latest stable
addons:
  apt:
    packages:
      - google-chrome-stable

# git configs
git:
  depth: 1

# Define the php versions against we want to test our code
php:
  # - 5.6
  - 7.0
  # - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer update
 
sudo: false

before_script:
    - composer install

script:
  - |
    php -S localhost:8000 -t public &
    vendor/bin/codecept run

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master
