# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

# Tell Travis CI we are using PHP
language: php

# The platforms you wants to test on
dist: trusty
os:
  - linux

# Install google chrome latest stable
addons:
  apt:
    packages:
      - google-chrome-stable

# git configs
git:
  depth: 1

# Define the php versions against we want to test our code
php:
  - 5.6
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0


# We don't want to run linux commands as super user
# false means Travis will run this in a container
sudo: false
before_script:
    - composer install
    - composer require superhabber/millcore
    
# Disable x-debug to speed up things

script:
  - |
    php -S localhost:8000 -t public > /dev/null 2>&1 &
    vendor/bin/codecept run

#after_success:

#after_failure:


# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# Cache folder, you can delete cache from Travis CI web interface
cache:
    directories:
        - vendor
        - $HOME/.composer/cache