language: php
php:
  - 7.1.0
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction
script:
  - |
    vendor/bin/codecept run
  
