#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/vendor/mill/libs/basic/aliases.php';
/**
 * for db using
 */
new \mill\core\base\Model();
new \mill\core\console\Handler($argv);





